version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nutrition_user
      POSTGRES_PASSWORD: nutrition_pass
      POSTGRES_DB: nutrition
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - nutrition-net

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://nutrition_user:nutrition_pass@db:5432/nutrition
      WATCHFILES_FORCE_POLLING: "true"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Backend:/app/Backend
      - ./alembic.ini:/app/alembic.ini:ro
    command: uvicorn Backend.backend:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - nutrition-net
    ports:
      - "${BACKEND_PORT:-8000}:8000"

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
      target: dev
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - nutrition-net

volumes:
  dbdata:
  node_modules:
    name: "${COMPOSE_PROJECT_NAME:-nutrition}_node_modules"


networks:
  nutrition-net:
