[tool.black]
line-length = 100
target-version = ["py311"]
include = "(Backend|Database|scripts)/.*[.]py$"
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["Backend", "Database"]
combine_as_imports = true
force_single_line = false

