INSERT INTO ingredients (name) VALUES ('Atlantic Salmon');
INSERT INTO ingredients (name) VALUES ('Steelhead Trout');
INSERT INTO ingredients (name) VALUES ('Alaskan Cod');
INSERT INTO ingredients (name) VALUES ('Tilapia');
INSERT INTO ingredients (name) VALUES ('Imitation Crab');
INSERT INTO ingredients (name) VALUES ('Chicken Breast');
INSERT INTO ingredients (name) VALUES ('Rotisserie Chicken');
INSERT INTO ingredients (name) VALUES ('Egg White');
INSERT INTO ingredients (name) VALUES ('Egg Yolk');
INSERT INTO ingredients (name) VALUES ('Egg');
INSERT INTO ingredients (name) VALUES ('Beef Steak');
INSERT INTO ingredients (name) VALUES ('Bacon');
INSERT INTO ingredients (name) VALUES ('Feta Cheese');
INSERT INTO ingredients (name) VALUES ('Parmesan Cheese');
INSERT INTO ingredients (name) VALUES ('Greek Yogurt (Oikos Triple 0 Vanilla)');
INSERT INTO ingredients (name) VALUES ('Brown Rice (raw)');
INSERT INTO ingredients (name) VALUES ('White Rice (raw)');
INSERT INTO ingredients (name) VALUES ('Mission Flour Tortilla (Regular)');
INSERT INTO ingredients (name) VALUES ('Mission Flour Tortilla (Small)');
INSERT INTO ingredients (name) VALUES ('Breadcrumb');
INSERT INTO ingredients (name) VALUES ('Oatmeal Steel Cut (raw)');
INSERT INTO ingredients (name) VALUES ('Corn');
INSERT INTO ingredients (name) VALUES ('Quinoa (raw)');
INSERT INTO ingredients (name) VALUES ('Chia/Flax/Hemp Seed Blend');
INSERT INTO ingredients (name) VALUES ('Hemp Heart');
INSERT INTO ingredients (name) VALUES ('Arrowroot Flour');
INSERT INTO ingredients (name) VALUES ('Pistachio');
INSERT INTO ingredients (name) VALUES ('Walnut');
INSERT INTO ingredients (name) VALUES ('Cashew');
INSERT INTO ingredients (name) VALUES ('Sourdough Bread');
INSERT INTO ingredients (name) VALUES ('Whole Grain Bread');
INSERT INTO ingredients (name) VALUES ('Ezekiel Bread');
INSERT INTO ingredients (name) VALUES ('Brioche Bread Thick Cut');
INSERT INTO ingredients (name) VALUES ('Black Bean');
INSERT INTO ingredients (name) VALUES ('Garbanzo Bean');
INSERT INTO ingredients (name) VALUES ('Broccoli');
INSERT INTO ingredients (name) VALUES ('Baby Spinach');
INSERT INTO ingredients (name) VALUES ('Spinach');
INSERT INTO ingredients (name) VALUES ('Arugula');
INSERT INTO ingredients (name) VALUES ('Kale');
INSERT INTO ingredients (name) VALUES ('Iceberg Lettuce');
INSERT INTO ingredients (name) VALUES ('Red Cabbage');
INSERT INTO ingredients (name) VALUES ('Cabbage');
INSERT INTO ingredients (name) VALUES ('Cucumber');
INSERT INTO ingredients (name) VALUES ('Tomato');
INSERT INTO ingredients (name) VALUES ('Grape Tomato');
INSERT INTO ingredients (name) VALUES ('Avocado');
INSERT INTO ingredients (name) VALUES ('Sweet Potato');
INSERT INTO ingredients (name) VALUES ('Butternut Squash');
INSERT INTO ingredients (name) VALUES ('Russet Potato');
INSERT INTO ingredients (name) VALUES ('Red Potato');
INSERT INTO ingredients (name) VALUES ('Gold Potato');
INSERT INTO ingredients (name) VALUES ('Red Onion');
INSERT INTO ingredients (name) VALUES ('White Onion');
INSERT INTO ingredients (name) VALUES ('Yellow Onion');
INSERT INTO ingredients (name) VALUES ('Green Onion');
INSERT INTO ingredients (name) VALUES ('Shallot');
INSERT INTO ingredients (name) VALUES ('Baby Carrot');
INSERT INTO ingredients (name) VALUES ('Carrot');
INSERT INTO ingredients (name) VALUES ('Green Bell Pepper');
INSERT INTO ingredients (name) VALUES ('Orange Bell Pepper');
INSERT INTO ingredients (name) VALUES ('Red Bell Pepper');
INSERT INTO ingredients (name) VALUES ('Yellow Bell Pepper');
INSERT INTO ingredients (name) VALUES ('White Button Mushroom');
INSERT INTO ingredients (name) VALUES ('Sweet Pea');
INSERT INTO ingredients (name) VALUES ('Cauliflower');
INSERT INTO ingredients (name) VALUES ('Garlic');
INSERT INTO ingredients (name) VALUES ('Beet');
INSERT INTO ingredients (name) VALUES ('Blueberry');
INSERT INTO ingredients (name) VALUES ('Banana');
INSERT INTO ingredients (name) VALUES ('Raspberry');
INSERT INTO ingredients (name) VALUES ('Strawberry');
INSERT INTO ingredients (name) VALUES ('Mango');
INSERT INTO ingredients (name) VALUES ('Lemon Juice');
INSERT INTO ingredients (name) VALUES ('Kiwi');
INSERT INTO ingredients (name) VALUES ('Watermelon');
INSERT INTO ingredients (name) VALUES ('Olive Oil Extra Virgin');
INSERT INTO ingredients (name) VALUES ('Sesame Oil');
INSERT INTO ingredients (name) VALUES ('Avocado Oil');
INSERT INTO ingredients (name) VALUES ('Coconut Oil');
INSERT INTO ingredients (name) VALUES ('Butter');
INSERT INTO ingredients (name) VALUES ('Bacon Grease');
INSERT INTO ingredients (name) VALUES ('Soy Sauce');
INSERT INTO ingredients (name) VALUES ('Dijon Mustard');
INSERT INTO ingredients (name) VALUES ('Hemp Protein');
INSERT INTO ingredients (name) VALUES ('Nutritional Yeast');
INSERT INTO ingredients (name) VALUES ('PB2 Powdered Peanut Butter');
INSERT INTO ingredients (name) VALUES ('Peanut Butter');
INSERT INTO ingredients (name) VALUES ('Oat Milk');
INSERT INTO ingredients (name) VALUES ('Coconut Milk (Silk Original)');
INSERT INTO ingredients (name) VALUES ('Coconut Milk (Silk Unsweet)');
INSERT INTO ingredients (name) VALUES ('Granulated Sugar');
INSERT INTO ingredients (name) VALUES ('Honey');
INSERT INTO ingredients (name) VALUES ('Yogurt Covered Pretzel');
INSERT INTO ingredients (name) VALUES ('Molasses');
INSERT INTO ingredients (name) VALUES ('Brown Sugar');
INSERT INTO ingredients (name) VALUES ('Tomato Paste');
INSERT INTO ingredients (name) VALUES ('Clif Bar Peanut Butter');
INSERT INTO ingredients (name) VALUES ('Gold Protein Powder (Vanilla)');
INSERT INTO ingredients (name) VALUES ('AG1');
