/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ingredients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Ingredients
         * @description Return all ingredients.
         */
        get: operations["get_all_ingredients_api_ingredients__get"];
        put?: never;
        /**
         * Add Ingredient
         * @description Create a new ingredient.
         */
        post: operations["add_ingredient_api_ingredients__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients/possible_tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Possible Tags
         * @description Return all possible ingredient tags ordered by name.
         */
        get: operations["get_all_possible_tags_api_ingredients_possible_tags_get"];
        put?: never;
        /**
         * Add Possible Tag
         * @description Create a new possible ingredient tag, or return existing on duplicate name.
         */
        post: operations["add_possible_tag_api_ingredients_possible_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingredients/{ingredient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingredient
         * @description Retrieve a single ingredient by ID.
         */
        get: operations["get_ingredient_api_ingredients__ingredient_id__get"];
        /**
         * Update Ingredient
         * @description Update an existing ingredient.
         *
         *     Important: Avoid deleting existing units on update to preserve referential
         *     integrity for rows in food_ingredients that reference them. Instead,
         *     upsert provided units (update by id or insert new). Existing units not in
         *     the payload are left unchanged.
         */
        put: operations["update_ingredient_api_ingredients__ingredient_id__put"];
        post?: never;
        /**
         * Delete Ingredient
         * @description Delete an ingredient.
         */
        delete: operations["delete_ingredient_api_ingredients__ingredient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Foods
         * @description Return all foods.
         */
        get: operations["get_all_foods_api_foods__get"];
        put?: never;
        /**
         * Add Food
         * @description Create a new food.
         */
        post: operations["add_food_api_foods__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/possible_tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Possible Food Tags
         * @description Return all possible food tags ordered by name.
         */
        get: operations["get_possible_food_tags_api_foods_possible_tags_get"];
        put?: never;
        /**
         * Add Possible Food Tag
         * @description Create a new possible food tag, or return existing on duplicate name.
         */
        post: operations["add_possible_food_tag_api_foods_possible_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/{food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Food
         * @description Retrieve a single food by ID.
         */
        get: operations["get_food_api_foods__food_id__get"];
        /**
         * Update Food
         * @description Update an existing food.
         */
        put: operations["update_food_api_foods__food_id__put"];
        post?: never;
        /**
         * Delete Food
         * @description Delete a food.
         */
        delete: operations["delete_food_api_foods__food_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description Return all saved plans ordered by last update descending.
         */
        get: operations["list_plans_api_plans__get"];
        put?: never;
        /**
         * Create Plan
         * @description Persist a new plan payload.
         */
        post: operations["create_plan_api_plans__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Plan
         * @description Retrieve a single plan by ID.
         */
        get: operations["get_plan_api_plans__plan_id__get"];
        /**
         * Update Plan
         * @description Update an existing plan.
         */
        put: operations["update_plan_api_plans__plan_id__put"];
        post?: never;
        /**
         * Delete Plan
         * @description Delete an existing plan.
         */
        delete: operations["delete_plan_api_plans__plan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stored_food/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stored Food
         * @description Retrieve stored food entries with optional filters.
         */
        get: operations["list_stored_food_api_stored_food__get"];
        put?: never;
        /**
         * Create Stored Food
         * @description Persist a new stored food entry.
         */
        post: operations["create_stored_food_api_stored_food__post"];
        /**
         * Clear Stored Food
         * @description Remove all stored food entries for a user.
         */
        delete: operations["clear_stored_food_api_stored_food__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stored_food/{stored_food_id}/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consume Stored Food
         * @description Consume portions from a stored food entry.
         */
        post: operations["consume_stored_food_api_stored_food__stored_food_id__consume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stored_food/{stored_food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Stored Food
         * @description Remove a stored food entry.
         */
        delete: operations["delete_stored_food_api_stored_food__stored_food_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{log_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Daily Logs
         * @description Return all log entries for a specific day.
         */
        get: operations["list_daily_logs_api_logs__log_date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Daily Log
         * @description Persist a new daily log entry.
         */
        post: operations["create_daily_log_api_logs__post"];
        /**
         * Clear Daily Logs
         * @description Remove daily log entries for a user, optionally filtered by day.
         */
        delete: operations["clear_daily_logs_api_logs__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Daily Log
         * @description Remove a single daily log entry.
         */
        delete: operations["delete_daily_log_api_logs__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usda/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Foods */
        get: operations["search_foods_api_usda_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usda/foods/{fdc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Food Details */
        get: operations["get_food_details_api_usda_foods__fdc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Report process liveness for container orchestrators.
         */
        get: operations["liveness_api_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Report readiness only when the API can reach the database.
         */
        get: operations["readiness_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and issue a session cookie.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session and clear the cookie.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Return the authenticated user's profile.
         */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change the current user's password and revoke their sessions.
         */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create User
         * @description Create a new user account.
         */
        post: operations["create_user_api_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthStatus
         * @description Current authentication state returned by auth endpoints.
         */
        AuthStatus: {
            /** Authenticated */
            authenticated: boolean;
            user?: components["schemas"]["UserRead"] | null;
        };
        /**
         * ChangePasswordRequest
         * @description Payload for changing the current user's password.
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * DailyLogEntryCreate
         * @description Schema for creating a new daily log entry.
         */
        DailyLogEntryCreate: {
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Stored Food Id */
            stored_food_id?: number | null;
            /** Ingredient Id */
            ingredient_id?: number | null;
            /** Food Id */
            food_id?: number | null;
            /** Portions Consumed */
            portions_consumed: number;
            /** Calories */
            calories: number;
            /** Protein */
            protein: number;
            /** Carbohydrates */
            carbohydrates: number;
            /** Fat */
            fat: number;
            /** Fiber */
            fiber: number;
        };
        /**
         * DailyLogEntryRead
         * @description Schema returned when reading daily log entries.
         */
        DailyLogEntryRead: {
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Stored Food Id */
            stored_food_id?: number | null;
            /** Ingredient Id */
            ingredient_id?: number | null;
            /** Food Id */
            food_id?: number | null;
            /** Portions Consumed */
            portions_consumed: number;
            /** Calories */
            calories: number;
            /** Protein */
            protein: number;
            /** Carbohydrates */
            carbohydrates: number;
            /** Fat */
            fat: number;
            /** Fiber */
            fiber: number;
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FoodCreate
         * @description Schema for creating a food.
         */
        FoodCreate: {
            /** Name */
            name: string;
            /** Ingredients */
            ingredients?: components["schemas"]["FoodIngredientCreate"][];
            /** Tags */
            tags?: components["schemas"]["TagRef"][];
        };
        /**
         * FoodIngredient
         * @description Link between a food and an ingredient with quantity information.
         */
        FoodIngredient: {
            /** Ingredient Id */
            ingredient_id?: number | null;
            /** Food Id */
            food_id?: number | null;
            /** Unit Id */
            unit_id?: number | null;
            /** Unit Quantity */
            unit_quantity?: number | null;
        };
        /**
         * FoodIngredientCreate
         * @description Schema for creating food ingredient linkage.
         */
        FoodIngredientCreate: {
            /** Ingredient Id */
            ingredient_id: number;
            /** Unit Id */
            unit_id?: number | null;
            /** Unit Quantity */
            unit_quantity?: number | null;
        };
        /**
         * FoodRead
         * @description Schema for reading food data.
         */
        FoodRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id?: string | null;
            /** Name */
            name: string;
            /** Ingredients */
            ingredients?: components["schemas"]["FoodIngredient"][];
            /** Tags */
            tags?: components["schemas"]["PossibleFoodTag"][];
        };
        /**
         * FoodUpdate
         * @description Schema for updating a food.
         */
        FoodUpdate: {
            /** Name */
            name: string;
            /** Ingredients */
            ingredients?: components["schemas"]["FoodIngredientCreate"][];
            /** Tags */
            tags?: components["schemas"]["TagRef"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngredientCreate
         * @description Schema for creating an ingredient.
         */
        IngredientCreate: {
            /** Name */
            name: string;
            /** Source */
            source?: string | null;
            /** Source Id */
            source_id?: string | null;
            nutrition?: components["schemas"]["NutritionCreate"] | null;
            /** Units */
            units?: components["schemas"]["IngredientUnitCreate"][];
            /** Tags */
            tags?: components["schemas"]["TagRef"][];
            /** Shopping Unit Id */
            shopping_unit_id?: number | null;
            shopping_unit?: components["schemas"]["IngredientShoppingUnitSelection"] | null;
        };
        /**
         * IngredientRead
         * @description Schema for reading ingredient data.
         */
        IngredientRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id?: string | null;
            /** Name */
            name: string;
            /** Source */
            source?: string | null;
            /** Source Id */
            source_id?: string | null;
            nutrition?: components["schemas"]["Nutrition"] | null;
            /** Units */
            units?: components["schemas"]["IngredientUnit"][];
            /** Tags */
            tags?: components["schemas"]["PossibleIngredientTag"][];
            /** Shopping Unit Id */
            shopping_unit_id?: number | null;
            shopping_unit?: components["schemas"]["IngredientUnit"] | null;
        };
        /**
         * IngredientShoppingUnitSelection
         * @description Payload for selecting a preferred shopping unit.
         */
        IngredientShoppingUnitSelection: {
            /** Unit Id */
            unit_id?: number | null;
            /** Name */
            name?: string | null;
            /** Grams */
            grams?: number | null;
        };
        /**
         * IngredientUnit
         * @description Measurement unit for an ingredient.
         */
        IngredientUnit: {
            /** Id */
            id?: number | null;
            /** Ingredient Id */
            ingredient_id?: number | null;
            /** Name */
            name: string;
            /** Grams */
            grams: number;
        };
        /**
         * IngredientUnitCreate
         * @description Schema for creating ingredient unit data.
         */
        IngredientUnitCreate: {
            /** Name */
            name: string;
            /** Grams */
            grams: number;
        };
        /**
         * IngredientUnitUpdate
         * @description Schema for updating ingredient unit data (allows id for upsert).
         */
        IngredientUnitUpdate: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /** Grams */
            grams: number;
        };
        /**
         * IngredientUpdate
         * @description Schema for updating an ingredient.
         */
        IngredientUpdate: {
            /** Name */
            name: string;
            /** Source */
            source?: string | null;
            /** Source Id */
            source_id?: string | null;
            nutrition?: components["schemas"]["NutritionCreate"] | null;
            /** Units */
            units?: components["schemas"]["IngredientUnitUpdate"][];
            /** Tags */
            tags?: components["schemas"]["TagRef"][];
            /** Shopping Unit Id */
            shopping_unit_id?: number | null;
            shopping_unit?: components["schemas"]["IngredientShoppingUnitSelection"] | null;
        };
        /**
         * LoginRequest
         * @description Credentials required to create a session.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Nutrition
         * @description Nutritional information for a single ingredient.
         */
        Nutrition: {
            /** Id */
            id?: number | null;
            /** Ingredient Id */
            ingredient_id?: number | null;
            /** Calories */
            calories: number;
            /** Fat */
            fat: number;
            /** Carbohydrates */
            carbohydrates: number;
            /** Protein */
            protein: number;
            /** Fiber */
            fiber: number;
        };
        /**
         * NutritionCreate
         * @description Schema for creating nutrition data.
         */
        NutritionCreate: {
            /** Calories */
            calories: number;
            /** Fat */
            fat: number;
            /** Carbohydrates */
            carbohydrates: number;
            /** Protein */
            protein: number;
            /** Fiber */
            fiber: number;
        };
        /**
         * PlanCreate
         * @description Payload required to persist a plan.
         */
        PlanCreate: {
            /** Label */
            label: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * PlanRead
         * @description Representation of a saved plan returned from the API.
         */
        PlanRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id?: string | null;
            /** Label */
            label: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PlanUpdate
         * @description Fields allowed when updating a persisted plan.
         */
        PlanUpdate: {
            /** Label */
            label?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * PossibleFoodTag
         * @description Tag that can be associated with a food.
         */
        PossibleFoodTag: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
        };
        /**
         * PossibleIngredientTag
         * @description Tag that can be associated with an ingredient.
         */
        PossibleIngredientTag: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
        };
        /**
         * StoredFoodConsume
         * @description Payload for consuming stored food portions.
         */
        StoredFoodConsume: {
            /** Portions */
            portions: number;
        };
        /**
         * StoredFoodCreate
         * @description Schema for creating stored food entries.
         */
        StoredFoodCreate: {
            /** Label */
            label?: string | null;
            /** Food Id */
            food_id?: number | null;
            /** Ingredient Id */
            ingredient_id?: number | null;
            /** Prepared Portions */
            prepared_portions: number;
            /** Per Portion Calories */
            per_portion_calories: number;
            /** Per Portion Protein */
            per_portion_protein: number;
            /** Per Portion Carbohydrates */
            per_portion_carbohydrates: number;
            /** Per Portion Fat */
            per_portion_fat: number;
            /** Per Portion Fiber */
            per_portion_fiber: number;
            /** Remaining Portions */
            remaining_portions?: number | null;
            /** Prepared At */
            prepared_at?: string | null;
        };
        /**
         * StoredFoodRead
         * @description Schema returned when reading stored food entries.
         */
        StoredFoodRead: {
            /** Label */
            label?: string | null;
            /** Food Id */
            food_id?: number | null;
            /** Ingredient Id */
            ingredient_id?: number | null;
            /** Prepared Portions */
            prepared_portions: number;
            /** Per Portion Calories */
            per_portion_calories: number;
            /** Per Portion Protein */
            per_portion_protein: number;
            /** Per Portion Carbohydrates */
            per_portion_carbohydrates: number;
            /** Per Portion Fat */
            per_portion_fat: number;
            /** Per Portion Fiber */
            per_portion_fiber: number;
            /** Id */
            id: number;
            /** User Id */
            user_id: string;
            /** Remaining Portions */
            remaining_portions: number;
            /** Is Finished */
            is_finished: boolean;
            /**
             * Prepared At
             * Format: date-time
             */
            prepared_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * TagCreate
         * @description Schema for creating a new possible tag by name.
         */
        TagCreate: {
            /** Name */
            name: string;
        };
        /**
         * TagRef
         * @description Reference to an existing tag by ID.
         */
        TagRef: {
            /** Id */
            id: number;
        };
        /** UsdaFoodSummary */
        UsdaFoodSummary: {
            /** Id */
            id?: number | null;
            /** Name */
            name?: string | null;
            nutrition?: components["schemas"]["UsdaNutrition"] | null;
            normalization: components["schemas"]["UsdaNormalizationMetadata"];
            /** Units */
            units?: components["schemas"]["UsdaFoodUnit"][];
        };
        /** UsdaFoodUnit */
        UsdaFoodUnit: {
            /** Name */
            name: string;
            /** Grams */
            grams: number;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** UsdaNormalizationMetadata */
        UsdaNormalizationMetadata: {
            /** Data Type */
            data_type?: string | null;
            /**
             * Source Basis
             * @enum {string}
             */
            source_basis: "per_100g" | "per_100ml" | "per_serving" | "unknown";
            /** Normalized Basis */
            normalized_basis?: "per_g" | null;
            /** Can Normalize */
            can_normalize: boolean;
            /** Reason */
            reason?: string | null;
            /** Serving Size */
            serving_size?: number | null;
            /** Serving Size Unit */
            serving_size_unit?: string | null;
            /** Household Serving Full Text */
            household_serving_full_text?: string | null;
        };
        /** UsdaNutrition */
        UsdaNutrition: {
            /** Calories */
            calories?: number | null;
            /** Protein */
            protein?: number | null;
            /** Fat */
            fat?: number | null;
            /** Carbohydrates */
            carbohydrates?: number | null;
            /** Fiber */
            fiber?: number | null;
        };
        /** UsdaSearchResponse */
        UsdaSearchResponse: {
            /** Foods */
            foods: components["schemas"]["UsdaFoodSummary"][];
        };
        /**
         * UserCreate
         * @description Payload for an admin-created user account.
         */
        UserCreate: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /**
         * UserRead
         * @description Safe user representation returned to clients.
         */
        UserRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Is Active */
            is_active: boolean;
            /** Is Admin */
            is_admin: boolean;
            /** Last Login At */
            last_login_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_all_ingredients_api_ingredients__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"][];
                };
            };
        };
    };
    add_ingredient_api_ingredients__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_possible_tags_api_ingredients_possible_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PossibleIngredientTag"][];
                };
            };
        };
    };
    add_possible_tag_api_ingredients_possible_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PossibleIngredientTag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingredient_api_ingredients__ingredient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ingredient_api_ingredients__ingredient_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ingredient_api_ingredients__ingredient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingredient_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_foods_api_foods__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodRead"][];
                };
            };
        };
    };
    add_food_api_foods__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_possible_food_tags_api_foods_possible_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PossibleFoodTag"][];
                };
            };
        };
    };
    add_possible_food_tag_api_foods_possible_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PossibleFoodTag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_food_api_foods__food_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_food_api_foods__food_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_food_api_foods__food_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_plans__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"][];
                };
            };
        };
    };
    create_plan_api_plans__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_plans__plan_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_plan_api_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stored_food_api_stored_food__get: {
        parameters: {
            query?: {
                only_available?: boolean;
                day?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredFoodRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stored_food_api_stored_food__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoredFoodCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredFoodRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_stored_food_api_stored_food__delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    consume_stored_food_api_stored_food__stored_food_id__consume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stored_food_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoredFoodConsume"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredFoodRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_stored_food_api_stored_food__stored_food_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stored_food_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_daily_logs_api_logs__log_date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_daily_log_api_logs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyLogEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyLogEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_daily_logs_api_logs__delete: {
        parameters: {
            query?: {
                log_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_daily_log_api_logs__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_foods_api_usda_search_get: {
        parameters: {
            query: {
                query: string;
                data_types?: ("Foundation" | "SR Legacy" | "Survey (FNDDS)" | "Branded" | "Experimental")[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsdaSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_food_details_api_usda_foods__fdc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fdc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsdaFoodSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_api_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_auth_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
