"""sync_models_20250919_161747

Revision ID: c9271ea398b2
Revises: d3f0b1c2e7ad
Create Date: 2025-09-19 16:17:47.596917
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9271ea398b2'
down_revision = 'd3f0b1c2e7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_label'), table_name='plans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_plans_label'), 'plans', ['label'], unique=False)
    # ### end Alembic commands ###
