name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      DATABASE_URL: sqlite:///./app.db
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.11'
      - name: Cache backend dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: backend-${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('Backend/requirements.txt') }}
          restore-keys: |
            backend-${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-
      - name: Verify pip cache
        run: ls -al ~/.cache/pip || echo 'No pip cache found'
      - name: Install backend dependencies
        run: |
          source scripts/activate-venv.sh
          pip install pytest
      - name: Run Alembic migrations
        run: |
          source scripts/activate-venv.sh
          alembic upgrade head
      - name: Backend tests
        run: |
          source scripts/activate-venv.sh
          pytest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: '20'
      - name: Cache frontend dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: frontend-${{ runner.os }}-npm-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('Frontend/nutrition-frontend/package-lock.json') }}
          restore-keys: |
            frontend-${{ runner.os }}-npm-${{ steps.setup-node.outputs.node-version }}-
      - name: Verify npm cache
        run: ls -al ~/.npm || echo 'No npm cache found'
      - name: Install frontend dependencies
        working-directory: Frontend/nutrition-frontend
        run: npm ci
      - name: Frontend tests
        working-directory: Frontend/nutrition-frontend
        env:
          CI: true
        run: npm test -- --watchAll=false
